const mongoose = require("mongoose")
const subcategories = [
    "Movie",
    "Theather",
    "Museums",
    "Show Houses",
    "Malls",
    "Beach Clubs",
    "Playgrounds",
    "SPA",
    "Traditional",
    "Oriental",
    "Contemporary",
    "Mexican",
    "Italian",
    "French",
    "Portuguese",
    "Arabic",
    "Vegan",
    "Steakhouse",
    "African",
    "Coffee Shops",
    "Bruncheria",
    "Trendy",
    "Pizzeria",
    "Laundry",
    "Beauty Salon",
    "Podiatry / Manicure",
    "Braid Designer",
    "Gym",
    "Cosmetic Story",
    "Babershop",
    "Exchange House",
    "Phone Assitance",
    "Tailoring",
    "Supermarket",
    "Taxi Company",
    "Catamaran Morro de SP",
    "Bus to Chapada",
    "Boat Boipeba - Valenca",
    "Ferry Boat",
    "Speedboat Salvador - Itaparica",
    "Transfer Salvado Airport - Chapada",
    "Clinics",
    "Hospital",
    "Laboratories",
    "Dentist"
  ]

module.exports = subcategories 